### ISSUE TITLE
Report: env: can't execute 'bash': No such file or directory

### ISSUE THREAD

**Issue by brainwang** [jlordiales/jyparser#3]
I pull the image with:
`docker pull jlordiales/jyparser`

and then try the example:
 `cat demo-deployment.yaml | docker run -i --rm jlordiales/jyparser get ".spec.replicas"`
It prompt:
`env: can't execute 'bash': No such file or directory`

What is wrong?

My docker info:
<pre>
[root@devvm13 tmp]# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 1.13.0
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-229.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.1 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67 GiB
Name: devvm13
ID: XPVV:LNYA:SUTQ:OB6R:PBHH:L22V:FTQH:RFBC:4VYI:UOIF:L722:7QP6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://16.85.88.10:8080/
No Proxy: docker-registry
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 docker-registry:5000
 127.0.0.0/8
Live Restore Enabled: false
</pre>

The demo-deployment.yaml  file:
<pre>
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo
spec:  #DeploymentSpec
  replicas: 1
  template: #PodTemplateSpec
    metadata:
    # the name is not included in the meta data as a unique name is generated from the deployment name
      labels:
        app: demo
    spec: #PodSpec
      containers: #Container array
      - name: demo
        image: docker-registry:5000/eium8.3.0.demo:centos7
        env:
        - name: GET_HOSTS_FROM
          value: env
        command: ["/root/start.sh"]

###Any problem, contact Wang, Bo (bow@hpe.com)
</pre>

**Comment by jlordiales** [comment]
Hey @brainwang!
Sorry about that, I merged a PR recently that broke the main script. I've pushed a new image with the fix. If you pull again now it should hopefully work.
