### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by IdanAdar** [jlordiales/jyparser#5]
I'd like to run this locally, so I did `./start.sh req`, which resulted with: 

```
python modules missing in [yaml, json]
```

I am not sure what this error mean. Which modules are missing?

**Comment by bonidier** [comment]
Hi @IdanAdar, this a message nice my pull request #2. 
Your host OS need python module Yaml and/or Json

For sure the message can be improved, to only show missing modules.

**Comment by jlordiales** [comment]
@IdanAdar: like @bonidier mentioned, if you want to run the script locally you need to have python and the PyYaml module (you can install it with pip) as well as jq.
